### ISSUE TITLE
Etc: Next.js 공식문서 - 학습과정 읽기

### ISSUE THREAD

**Issue by shinhyojeong** [price-offer/Team_Price_Offer_FE#15]
### 📌 작업 내용

- Next.js 공식문서 - 학습과정 읽기

### ✅ 상세 작업

- [ ] Dynamic Routes
- [ ] API Routes
- [ ] Deploying Your Next.js App
- [ ] Introduction to SEO
- [ ] TypeScript

### 👉 시작일

- 2/3

### 👏 종료일

- 2/4

**Comment by sonsurim** [comment]
ㅠㅠ 효정님이 바쁘신 관계로,, 이슈를 닫았습니다.
